# Generated by Django 4.0.4 on 2022-07-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=12, upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
