# Generated by Django 4.0.4 on 2022-07-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil ', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
