# Generated by Django 4.0.4 on 2022-06-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=269, null=True)),
                ('difficulty_hard', models.BooleanField(default=True)),
            ],
        ),
    ]
