# Generated by Django 4.0.4 on 2022-06-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='student_qty',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
    ]
