# Generated by Django 4.0.4 on 2022-06-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_student_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=69, unique=True),
        ),
    ]
