# Generated by Django 4.0.4 on 2022-06-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_estudiante_trabajo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
