# Generated by Django 4.0.4 on 2022-07-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='trabajo',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
    ]
