# Generated by Django 4.0.4 on 2022-07-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courses_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajo',
        ),
    ]
